---
# tasks file for ucn_proxy

- name: copy container image for UCN proxy
  copy: src=ucn-proxy-image.tar dest=/var/contiv

- name: load UCN proxy image
  shell: docker load -i /var/contiv/ucn-proxy-image.tar

- name: copy shell script for starting ucn-proxy
  template: src=ucn_proxy.j2 dest=/usr/bin/ucn_proxy.sh mode=u=rwx,g=rx,o=rx

- name: create cert folder for proxy
  file: path=/var/contiv/certs/ state=directory

- name: copy cert for starting ucn-proxy
  copy: src=cert.pem dest=/var/contiv/certs/ucn_cert.pem mode=u=rw,g=r,o=r

- name: copy key for starting ucn-proxy
  copy: src=key.pem dest=/var/contiv/certs/ucn_key.pem mode=u=rw,g=r,o=r

- name: copy systemd units for ucn-proxy
  copy: src=ucn-proxy.service dest=/etc/systemd/system/ucn-proxy.service

- name: initialize ucn-proxy
  shell: /usr/bin/ucn_proxy.sh init

- name: start ucn-proxy container
  service: name=ucn-proxy state=started
