# netplugin-node hosts set up netmast/netplugin in a cluster
- hosts: netplugin-node
  become: true
  environment: '{{ env }}'
  roles:
    - { role: contiv_network, run_as: master, scheduler_provider: native-swarm  }
